# -*- coding: utf-8 -*-
"""Append NEET PG 2026 practice paper (generated by workflow) to bank.js."""
import io, json, re, sys

BANK_PATH = 'questions/bank.js'
PAPER_PATH = r'C:\Users\navne\AppData\Local\Temp\claude\F--NEET-PG\7f70972e-7f7a-41c2-9f48-027968bd8703\tasks\wotttlyuu.output'

def load_bank():
    src = io.open(BANK_PATH, encoding='utf-8').read()
    m = re.search(r'window\.QUESTIONS\s*=\s*(\[.*\])\s*;', src, re.S)
    if not m:
        print('Cannot parse bank.js', file=sys.stderr)
        sys.exit(1)
    return json.loads(m.group(1))

def save_bank(bank):
    out = []
    out.append('// NEET PG / INI-CET practice bank — reconstructed from curated + deep-research expansions.')
    out.append('// Sources tagged per-item: src="curated", "expand", "medink", "generated".')
    out.append('window.QUESTIONS = ')
    out.append(json.dumps(bank, ensure_ascii=False, indent=0))
    out.append('\n;')
    io.open(BANK_PATH, 'w', encoding='utf-8').write('\n'.join(out))
    print('Bank saved, total', len(bank))

def main():
    raw = io.open(PAPER_PATH, encoding='utf-8').read()
    # task output is JSON: {"summary":..., "result":{"paper":[...]}}
    data = json.loads(raw)
    paper = data['result']['paper']
    print('paper questions:', len(paper))
    # validate shape
    bad = 0
    for q in paper:
        if not (isinstance(q.get('o'), list) and len(q['o']) == 4
                and isinstance(q.get('a'), int) and 0 <= q['a'] <= 3
                and q.get('q') and q.get('ex')):
            bad += 1
    print('malformed:', bad)
    if bad:
        sys.exit(1)
    bank = load_bank()
    existing_q = set(q.get('q')[:60] for q in bank)
    added = 0
    for q in paper:
        qn = {'q': q['q'], 'o': q['o'], 'a': q['a'], 'ex': q['ex'],
              'e': 'NEET PG', 'y': '2026', 's': q.get('s', 'Medicine'), 'src': 'generated'}
        if qn['q'][:60] in existing_q:
            continue
        bank.append(qn)
        added += 1
    print('added:', added)
    save_bank(bank)

if __name__ == '__main__':
    main()
