# -*- coding: utf-8 -*-
"""Rebuild 24 corrupted questions with source-verified content."""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')
B = json.load(open(r'F:\NEET PG\research\corrected_bank.json', encoding='utf-8'))
byid = {q['qid']: q for q in B}

FIX = {
'q1397': ('Based on the given electron microscopy image, match the items to their respective sarcomere structures.',
    ['a-2, b-3, c-1, d-4', 'a-1, b-2, c-3, d-4', 'a-4, b-3, c-1, d-2', 'a-3, b-2, c-1, d-4'], 0,
    'The image shows a diagram of a sarcomere, the functional unit of striated muscle. A points to the central, lighter region within the A-band where there are only thick (myosin) filaments — the H-zone (a-2). B brackets the entire length of the thick filaments, including overlapping regions with thin filaments — the A-band (b-3). C brackets the lighter region containing only thin (actin) filaments, bisected by the Z-line — the I-band (c-1). D points to the dark line in the middle of the I-band, the Z-line, which anchors the thin filaments and defines the sarcomere boundary (d-4). Therefore, the correct matching is a-2, b-3, c-1, d-4.'),
'q1558': ('Please match the given columns based on Epidemiology Guidelines: a. CARE, b. CONSORT, c. PRISMA, d. Observational study guideline',
    ['A2-B1-C4-D3', 'A1-B2-C3-D4', 'A3-B4-C2-D1', 'A4-B3-C1-D2'], 0,
    'CARE (CAse REport) guidelines are designed for transparent reporting of case reports (a -> 2). CONSORT (CONsolidated Standards of Reporting Trials) is the guideline for reporting Randomized Controlled Trials (b -> 1). PRISMA (Preferred Reporting Items for Systematic Reviews and Meta-Analyses) provides a checklist for reporting systematic reviews and meta-analyses (c -> 4). STROBE and MOOSE are guidelines for reporting observational studies such as cohort, case-control, and cross-sectional studies (d -> 3).'),
'q1601': ('In an elderly patient with meningitis, whose CSF is evaluated using Gram stain and microscopy, what motility pattern is expected for the most likely causative organism shown in the image?',
    ['Motile at 22\u00b0C and non-motile at 37\u00b0C', 'No motility at 22\u00b0C and motile at 37\u00b0C', 'Motile at both 37\u00b0C and 22\u00b0C', 'Non-motile at both 37\u00b0C and 22\u00b0C'], 0,
    'Listeria monocytogenes, a Gram-positive bacillus, is a significant cause of meningitis in neonates, the elderly, and immunocompromised individuals. A key distinctive laboratory feature is its temperature-dependent motility: in broth at room temperature (22-25\u00b0C) it exhibits characteristic end-over-end "tumbling motility" on wet mount, due to peritrichous flagella. At 37\u00b0C the expression of flagellar genes is downregulated and the bacterium becomes non-motile. This unique characteristic of being motile at room temperature but non-motile at 37\u00b0C helps differentiate Listeria monocytogenes from morphologically similar Gram-positive bacilli such as Corynebacterium species.'),
'q1624': ('How would you describe the characteristic murmur of aortic regurgitation?',
    ['Ventricular contraction', 'Ejection systolic murmur', 'Diastolic murmur', 'Systolic murmur'], 2,
    'Aortic regurgitation (or aortic insufficiency) is a condition where the aortic valve fails to close completely at the end of systole, allowing blood to leak backward from the aorta into the left ventricle during diastole. This retrograde flow generates the characteristic murmur, which is a diastolic murmur — typically a high-pitched, blowing, decrescendo murmur best heard at the left sternal border with the patient sitting up and leaning forward in full expiration, beginning immediately after S2. In contrast, an ejection systolic murmur (B) is caused by forward flow through a narrowed (stenotic) aortic or pulmonary valve during systole.'),
'q1672': ('Match the following conditions with their corresponding syndromes: a. Trisomy 13 1. Huntington disease, b. Trisomy 18 2. Patau syndrome, c. Trinucleotide repeat sequence 3. Sickle disease, d. Hb point mutation of glutamate to valine 4. Edward syndrome',
    ['a2-b4-c1-d3', 'b1-a3-d2-c4', 'a2-b1-c4-d3', 'a4-b1-c3-d2'], 0,
    'Trisomy 13 is the chromosomal abnormality that causes Patau syndrome (a - 2). Trisomy 18 is responsible for Edward syndrome, characterized by low-set ears, small jaw, and clenched fists with overlapping fingers (b - 4). Huntington disease is a neurodegenerative disorder caused by a trinucleotide repeat expansion in the huntingtin gene (c - 1). Sickle cell disease is caused by a point mutation in the beta-globin gene substituting glutamic acid with valine at position 6 (d - 3). Correct matching: a2-b4-c1-d3.'),
'q1791': ('A patient has had a fever for 3 days, and CBC shows a platelet count below 90,000. Dengue is suspected. Which of the following tests cannot be performed on day 3 of illness?',
    ['PCR', 'NS1', 'IgM ELISA', 'Xenodiagnosis using culture in Aedes mosquito'], 2,
    'During a primary dengue infection, the virus and viral components are detectable first, followed by the host immune response. On day 3 the patient is typically in the acute viremic phase: PCR (detecting viral RNA) would be positive, the NS1 antigen is detectable from day 1 up to day 9, and xenodiagnosis would be possible as the mosquito could become infected by feeding on the viremic patient. In contrast, the host antibody response takes time — IgM antibodies detected by ELISA usually do not appear until day 4-5. Therefore, on day 3, an IgM ELISA is the least likely test to be positive.'),
'q1811': ('Comment on the lung disease based on the flow-volume loop.',
    ['Hypersensitivity pneumonitis', 'Sarcoidosis', 'Acute respiratory distress syndrome', 'Bronchiectasis'], 3,
    'The flow-volume loop shown demonstrates a classic obstructive pattern, with a "scooped-out" or concave appearance of the descending (expiratory) limb, indicating dynamic airflow reduction during forced expiration. While total volume may be normal or slightly reduced, peak expiratory flow is decreased and flow rate drops off rapidly. Among the options, bronchiectasis is an obstructive lung disease characterized by permanent airway dilation, chronic inflammation, and poor mucus clearance causing airflow limitation. In contrast, hypersensitivity pneumonitis, sarcoidosis, and ARDS typically produce a restrictive pattern — reduced lung volumes (FVC) with normal or increased FEV1/FVC ratio, giving a smaller "witchs hat" loop without scooping.'),
'q1844': ('A PAP smear from a 45-year-old woman with a left ovarian mass is shown. What is the most likely diagnosis?',
    ['Dysgerminoma', 'Dermoid', 'Granulosa cell tumor', 'Brenners'], 2,
    'The image displays Call-Exner bodies, pathognomonic microscopic structures for a granulosa cell tumor of the ovary — small, rosette-like formations of granulosa cells arranged around a central space containing eosinophilic, PAS-positive material. Granulosa cell tumors are sex cord-stromal tumors, the most common malignant stromal tumors, often producing estrogen, which can lead to endometrial hyperplasia or carcinoma. Although rare, tumor cells can sometimes be found on a Pap smear. The other tumors listed do not exhibit this characteristic feature.'),
'q1983': ('Match the following Wullstein classification with procedure/other name: a. Type II 1. Fenestration tympanoplasty, b. Type III 2. Graft placed over the incus, c. Type IV 3. Columella tympanoplasty, d. Type V 4. Cavum minor',
    ['a-2, b-3, c-4, d-1', 'a-1, b-2, c-3, d-4', 'a-3, b-4, c-1, d-2', 'a-4, b-1, c-2, d-3'], 0,
    'Wullstein classification describes tympanoplasty types based on the ossicular chain status and sound-conduction reconstruction. Type II involves a graft placed over the incus (a-2). Type III is performed when the malleus and incus are absent but the stapes is present and mobile — the graft is placed directly over the stapes head forming a columella effect, corresponding to Columella tympanoplasty (b-3). Type IV is done when only the stapes footplate is mobile — the graft protects the round window forming cavum minor (c-4). Type V refers to fenestration tympanoplasty, creating a new window in the lateral semicircular canal when the stapes footplate is fixed (d-1). Correct matching: a-2, b-3, c-4, d-1.'),
'q2020': ('Which of the following options can be employed to determine cardiac output? a. ECHO, b. Ventilation-perfusion scan, c. Thermodilution, d. Ficks principle',
    ['a,b,c,d', 'b,a,d', 'b,c,d', 'a,c,d'], 3,
    'Cardiac output (CO) is the amount of blood pumped by the heart per minute. ECHO (echocardiography) is a non-invasive method that estimates CO by measuring stroke volume and heart rate. Thermodilution (via a pulmonary artery catheter) is an invasive but accurate method based on the indicator-dilution principle. Ficks principle calculates CO from oxygen consumption and arteriovenous oxygen difference. In contrast, a ventilation-perfusion (V/Q) scan assesses pulmonary ventilation and perfusion matching, not cardiac output. Therefore the correct combination is a, c, d.'),
'q2098': ('What is the likely diagnosis for a baby who has delayed developmental milestones, hepatosplenomegaly, and the shown bone marrow microscopic findings?',
    ['Gaucher disease', 'Niemann-Pick disease', 'Hunter disease', 'Hurler disease'], 0,
    'The clinical triad of developmental delay, massive hepatosplenomegaly, and characteristic bone marrow findings strongly indicates Gaucher disease. The microscopic image displays Gaucher cells, pathognomonic for this condition — large macrophages (histiocytes) engorged with undigested glucocerebroside due to deficiency of the lysosomal enzyme glucocerebrosidase, giving the cytoplasm a distinctive fibrillary "wrinkled tissue paper" appearance. Niemann-Pick disease is characterized by foamy macrophages filled with sphingomyelin. Hunter and Hurler diseases are mucopolysaccharidoses with glycosaminoglycan accumulation, not Gaucher cells.'),
'q2106': ('Which medication is most likely to have caused hyperpigmentation of the palms and soles in an HIV-positive patient who has been on combination antiretroviral therapy (cART) for 5 months?',
    ['Nelfinavir', 'Emtricitabine', 'Abacavir', 'Zidovudine'], 1,
    'Hyperpigmentation of the skin, particularly the palms and soles, is a well-documented characteristic adverse effect of certain antiretrovirals. Among the options, Emtricitabine (FTC), a nucleoside reverse transcriptase inhibitor (NRTI) and component of many common first-line cART regimens (Truvada, Atripla, Descovy), is most famously associated with this side effect. The hyperpigmentation is generally benign and does not necessitate drug discontinuation, and is more common in darker skin. Zidovudine is more known for nail pigmentation and bone marrow suppression. Nelfinavir and Abacavir are not typically associated with this specific form.'),
'q2283': ('Please match the following eggs with their corresponding organisms.',
    ['1-A, 2-B, 3-C, 4-D', '1-C, 2-D, 3-A, 4-B', '1-D, 2-C, 3-A, 4-B', '1-B, 2-D, 3-C, 4-A'], 0,
    'The images show four distinct helminth eggs. Image A shows a small oval egg with a thin outer shell and inner membrane (oncosphere) containing six hooklets, with polar filaments — characteristic of Hymenolepis nana (1). Image B shows a large round egg with a thick mamillated (bumpy) outer corticated layer — the fertilized egg of Ascaris lumbricoides (2). Image C shows a moderately sized oval egg with a thin smooth shell containing a developing embryo at the 4-8 cell stage — Ancylostoma duodenale (3). Image D is the egg of Taenia solium (4). Correct matching: 1-A, 2-B, 3-C, 4-D.'),
'q2315': ('Which of the following methods is used for xenodiagnosis?',
    ['Rabbit ileal loop for enterotoxigenic Escherichia coli', 'Injecting Aedes thorax with blood of a suspected dengue patient', 'Injecting a hamster with splenic biopsy for diagnosis of leishmaniasis', 'Intradermal test on guinea pigs for toxigenicity of Corynebacterium diphtheriae'], 2,
    'Xenodiagnosis is a diagnostic method in which material from a suspected patient is inoculated into a living susceptible animal or vector, and the animal is later examined for development of the infection. It is used when direct detection in humans is difficult. In visceral leishmaniasis (kala-azar), organisms may be scanty in human samples; injecting splenic aspirate or biopsy material into a hamster allows the parasite to multiply, after which it can be detected in the animal tissues — a classical example of xenodiagnosis. The rabbit ileal loop is an experimental model for enterotoxin activity, injecting Aedes thorax is a viral isolation technique, and the guinea pig intradermal test assesses toxin production — none are true xenodiagnosis.'),
'q2380': ('What is the likely diagnosis in a young child who presents with mild, intermittent upper abdominal pain and has the X-ray shown below?',
    ['Bochdalek hernia', 'Morgagni hernia', 'Gastric volvulus', 'Eventration of diaphragm'], 0,
    'The chest X-ray shows multiple air-filled loops of bowel within the right hemithorax, with the heart and mediastinum shifted to the left — diagnostic of a congenital diaphragmatic hernia (CDH). The most common type is a Bochdalek hernia, a posterolateral defect occurring on the left side in about 85% of cases and right side in about 15%. While most are diagnosed in the neonatal period with severe respiratory distress, a smaller hernia, particularly on the right where the liver can plug the defect, may present later in childhood with milder intermittent symptoms like abdominal pain. A Morgagni hernia is an anterior defect; gastric volvulus is a twisting of the stomach.'),
'q2425': ('For which procedure are the following instruments used?',
    ['Pap smear', 'Hysteroscopy', 'Biopsy', 'Dilatation and curettage'], 0,
    'The instruments shown are used for performing a Pap smear (Papanicolaou test), a screening procedure for detecting premalignant and malignant lesions of the cervix. The set includes a vaginal speculum, Ayres spatula, endocervical brush, glass slides, and a fixative container. The speculum visualizes the cervix; the Ayres spatula scrapes cells from the ectocervix, particularly the transformation zone; the endocervical brush collects columnar epithelial cells. The material is spread on slides and fixed for microscopic examination. These instruments are not used for hysteroscopy, biopsy, or dilatation and curettage.'),
'q2448': ('If a patient has low blood oxygen (hypoxemia) but a normal alveolar-arterial (A-a) oxygen gradient, what medical condition does this typically point to?',
    ['Right to left shunt', 'Ventilation/perfusion (V/Q) mismatch', 'Hypoventilation', 'Alveolar membrane damage'], 2,
    'The A-a gradient is the difference between the partial pressure of oxygen in the alveoli (PAO2) and in arterial blood (PaO2), reflecting the efficiency of oxygen transfer across the lungs. An elevated gradient signifies a gas-exchange problem such as a shunt, V/Q mismatch, or diffusion impairment. However, if a patient is hypoxemic but the A-a gradient is normal, the lungs are transferring oxygen efficiently — the hypoxemia is caused by a low PAO2 to begin with. The two main causes are breathing air with a low oxygen concentration (e.g., high altitude) and hypoventilation, which increases arterial CO2, displacing oxygen in the alveoli and lowering PAO2 and consequently PaO2.'),
'q2482': ('By what mechanism did the injuries occur in a man brought to the emergency department after a blast, who presents with multiple small puncture wounds on the right side of the chest below the nipple, along with numerous small abrasions and bruises on the left lower abdomen?',
    ['Flying missiles', 'Blast of air', 'Explosion burns', 'Building collapse'], 0,
    'Blast injuries are categorized into primary, secondary, tertiary, and quaternary types. Multiple small puncture wounds, abrasions, and bruises are characteristic of secondary blast injuries, caused by flying missiles and fragments from the explosive device or surrounding environment (glass, wood, metal) propelled by the force of the explosion. Primary blast injuries are caused by the direct effect of the blast overpressure wave on gas-containing organs. Tertiary injuries result from the victim being thrown by the blast wind into a solid object. Quaternary injuries include burns and crush injuries from building collapse.'),
'q2610': ('What is the maximum level till which the lung reaches the liver?',
    ['A', 'B', 'C', 'D'], 1,
    'Anatomically, the right lung overlaps the liver through the diaphragm. The inferior border of the right lung in the mid-axillary line reaches the level of the 8th rib, while in the mid-clavicular line it reaches the 6th rib. The liver extends upward to about the 5th rib in the mid-clavicular line, so a significant portion of the superior surface of the liver is covered by the right lung. In the image, markings A, B, C, D represent descending levels over the liver surface; the lung reaches down to the level marked B, corresponding to the anatomical level where the inferior border of the lung overlaps the liver. Thus the maximum level corresponds to B, making option (B) correct.'),
'q2667': ('Which disease has an almost 100% fatality rate once symptoms develop?',
    ['Rabies', 'Nipah', 'Ebola', 'Measles'], 0,
    'Rabies is an acute progressive viral encephalitis transmitted to humans through the saliva of infected animals, typically via bites. Once clinical symptoms develop, rabies is almost universally fatal, with a case fatality rate approaching 100%. It is caused by the rabies virus, a neurotropic RNA virus of the Rhabdoviridae family. Post-exposure prophylaxis (wound care, rabies vaccine, and rabies immunoglobulin when indicated) is highly effective if administered before the onset of symptoms, which is why prompt treatment after exposure is critical.'),
'q2705': ('Which of the following is not an objective test?',
    ['Brainstem Evoked Response Audiometry (BERA)', 'Optical Coherence Tomography (OCT)', 'Impedance Audiometry', 'Pure Tone Audiometry'], 3,
    'Audiological tests are classified as objective or subjective (behavioral). Objective tests do not require a behavioral response; they measure a physiological response. BERA/ABR, Impedance Audiometry (tympanometry and acoustic reflex testing), and otoacoustic emissions are all objective tests. OCT is an objective imaging test used in ophthalmology. In contrast, Pure Tone Audiometry (PTA) is a subjective or behavioral test — the patient must listen to tones of specific frequencies and intensities and provide a conscious response (raising a hand or pressing a button), so the results depend entirely on patient perception and cooperation.'),
'q2726': ('A 40-year-old female undergoes cholecystectomy and later develops postoperative abdominal pain. Which test is used to detect a bile leak?',
    ['ERCP', 'MRCP', 'HIDA', 'CECT'], 2,
    'When a post-cholecystectomy bile leak is suspected, the most sensitive and specific functional imaging study to identify the leak is a HIDA scan (Hepatobiliary Iminodiacetic Acid scan), also known as cholescintigraphy. A radioactive tracer (technetium-99m labeled mebrofenin) is injected intravenously, taken up by hepatocytes, and excreted into the biliary system, mimicking bile flow. In a bile leak, the scan shows tracer flowing through the ducts but also abnormally extravasating into the peritoneal cavity, confirming the presence and often location of the leak. MRCP shows anatomy and ERCP is therapeutic; HIDA best demonstrates an active leak functionally.'),
'q1503': ('All of the following statements about Extrahepatic Biliary Atresia are true EXCEPT:',
    ['Kasai procedure should be done within 90 days', 'HIDA scan is used for diagnosis', 'Can be differentiated from other differential diagnoses by biopsy', 'Biliary atresia is the most common cause of neonatal cholestasis.'], 0,
    'Extrahepatic biliary atresia is a progressive inflammatory disease leading to fibrosis and obliteration of the extrahepatic bile ducts, the most common cause of pathological neonatal cholestasis and the most common indication for pediatric liver transplantation. A HIDA scan assesses biliary excretion — failure of tracer to reach the intestine is highly suggestive. A liver biopsy showing bile duct proliferation and portal tract fibrosis helps confirm the diagnosis. The definitive surgical treatment is the Kasai procedure (hepatic portoenterostomy), which should ideally be performed before 90 days of age — done within 60 days gives the best outcome.'),
'q1758': ('A patient shows reduced serum transferrin saturation. What is the most probable underlying condition?',
    ['Iron Deficiency Anemia', 'Hemochromatosis', 'Sideroblastic anemia', 'Pernicious anemia'], 0,
    'Transferrin saturation is calculated as (Serum Iron / Total Iron-Binding Capacity) \u00d7 100%. In Iron Deficiency Anemia (IDA), body iron stores are depleted: serum iron is low, and the liver increases transferrin production (high TIBC), resulting in significantly low transferrin saturation. In hemochromatosis, iron overload causes high serum iron and high saturation. Sideroblastic anemia features ring sideroblasts with iron accumulation in mitochondria. Pernicious anemia is a B12 deficiency unrelated to iron parameters.'),
}

for qid, (q, o, a, ex) in FIX.items():
    assert qid in byid, qid
    byid[qid]['q'] = q
    byid[qid]['o'] = o
    byid[qid]['a'] = a
    byid[qid]['ex'] = ex

json.dump(B, open(r'F:\NEET PG\research\corrected_bank.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('FIXED', len(FIX), 'questions')

# verify
byid2 = {q['qid']: q for q in B}
for qid in FIX:
    q = byid2[qid]
    assert len(q['o']) == 4, qid
    assert 0 <= q['a'] < 4, qid
    assert len(q['q']) > 20, qid
    assert len(q['ex']) > 100, qid
print('asserts passed')
