import json
d = json.load(open('research/orig_bank.json', encoding='utf-8'))
obg = [q for q in d if q.get('s') == 'OBG']
byid = {q['qid']: q for q in obg}

M = {
'q131': ('OBG','Ectopic Pregnancy','tubal ectopic implantation site'),
'q132': ('OBG','Molar Pregnancy','partial hydatidiform mole karyotype'),
'q133': ('OBG','Reproductive Physiology','oocyte meiosis arrest at ovulation'),
'q134': ('OBG','Reproductive Physiology','two-cell theory ovarian steroidogenesis'),
'q135': ('OBG','Postpartum Hemorrhage','most common cause of PPH'),
'q136': ('OBG','Uterine Fibroids','red degeneration fibroid in pregnancy'),
'q137': ('OBG','Ovarian Tumors','most common ovarian germ cell tumor dermoid'),
'q138': ('OBG','Preeclampsia & Eclampsia','MgSO4 toxicity antidote calcium gluconate'),
'q139': ('OBG','Gestational Trophoblastic Disease','choriocarcinoma lung metastasis'),
'q140': ('OBG','Ovarian Tumors','malignant germ cell tumor dysgerminoma'),
'q141': ('OBG','Breastfeeding Support','milk letdown oxytocin reflex'),
'q142': ('OBG','PCOS','ovulation induction anovulatory PCOS'),
'q610': ('OBG','Preeclampsia & Eclampsia','HELLP syndrome in severe preeclampsia'),
'q611': ('OBG','Preeclampsia & Eclampsia','MgSO4 Pritchard loading dose'),
'q612': ('OBG','Cord Prolapse','umbilical cord prolapse emergency'),
'q613': ('OBG','Shoulder Dystocia','shoulder dystocia maneuver sequence'),
'q637': ('OBG','Oligohydramnios','oligohydramnios cause renal agenesis'),
'q638': ('OBG','Gestational Trophoblastic Disease','high-risk GTN EMA-CO chemotherapy'),
'q639': ('OBG','Postpartum Hemorrhage','atomic PPH balloon tamponade next step'),
'q640': ('OBG','Uterine Rupture','suspected scar rupture during TOL'),
'q641': ('OBG','Episiotomy Repair','episiotomy repair layer sequence'),
'q642': ('OBG','Breech Delivery','Lovset maneuver extended arms'),
'q643': ('OBG','Medical Abortion','medical MTP 9 weeks mifepristone misoprostol'),
'q644': ('OBG','Obstetric History Notation','gravida parity twin notation'),
'q645': ('OBG','Cervical Cancer','FIGO IIIB cervical hydronephrosis'),
'q1151': ('OBG','Ovarian Tumors','serous adenocarcinoma advanced ovarian cancer'),
'q1152': ('OBG','Cervical Cancer','HPV 16 18 cervical cancer'),
'q1153': ('OBG','PCOS','Rotterdam criteria'),
'q1154': ('OBG','Postpartum Hemorrhage','drugs used in PPH'),
'q1155': ('OBG','Fetal Monitoring','causes of fetal bradycardia'),
'q1156': ('OBG','PCOS','enlarged ovaries delayed cycles PCOS'),
'q1157': ('OBG','Urinary Tract Infection in Pregnancy','E coli bacteriuria pregnancy'),
'q1158': ('OBG','Cervical Screening','Pap smear procedure'),
'q1159': ('OBG','Preeclampsia & Eclampsia','MgSO4 effects preeclampsia'),
'q1160': ('OBG','Urinary Tract Infection in Pregnancy','UTI in pregnancy complica'),
'q1161': ('OBG','IUD','LNG-IUCD insertion timing'),
'q1337': ('Pharmacology','Antidyslipidemic Drugs','Antara fenofibrate drug dose'),
'q1338': ('OBG','Multiple Pregnancy','twin chorionicity amnionicity'),
'q1339': ('OBG','Prenatal Screening','next test after quad screen'),
'q1340': ('OBG','Ectopic Pregnancy','ruptured ectopic hypovolemic shock'),
'q1341': ('OBG','Preterm Labour','antenatal steroids fetal lung maturity'),
'q1342': ('OBG','Postpartum Hemorrhage','methylergometrine contraindicated in HTN'),
'q1343': ('OBG','Preeclampsia & Eclampsia','severe preeclampsia 36 wk delivery'),
'q1344': ('OBG','Rh Incompatibility','postnatal Anti-D administration criterion'),
'q1345': ('OBG','Puerperium','lactation suppression cabergoline'),
'q1346': ('OBG','Infertility','zinc needed for fertility'),
'q1347': ('OBG','Instrumental Delivery','second stage outlet forceps'),
'q1348': ('OBG','Amenorrhea','imperforate hymen cyclical pain'),
'q1349': ('OBG','Reproductive Physiology','most potent estrogen estradiol'),
'q1350': ('OBG','Amenorrhea','Mullerian agenesis MRKH'),
'q1351': ('Paediatrics','Infant Growth','head circumference first 3 months'),
'q1352': ('OBG','Intrauterine Growth Restriction','IUGR criteria not used'),
'q1516': ('OBG','Pelvimetry','smallest pelvic diameter obstetric conjugate'),
'q1517': ('OBG','Instrumental Delivery','instrumental delivery contraindication CPD'),
'q1518': ('OBG','Preeclampsia & Eclampsia','early-onset eclampsia cutoff'),
'q1519': ('OBG','Physiological Changes in Pregnancy','pregnancy physiology changes'),
'q1520': ('OBG','Prenatal Screening','quadruple test markers'),
'q1521': ('Anatomy','Male Reproductive Histology','sperm mitochondria midpiece'),
'q1522': ('OBG','Ovarian Cysts','hemorrhagic ovarian cyst ultrasound'),
'q1523': ('OBG','Ectopic Pregnancy','ruptured ectopic MTX contraindicated'),
'q1524': ('OBG','Normal Labour','delayed cord clamping'),
'q1525': ('Paediatrics','Developmental Milestones','preschool milestone 4 years'),
'q1526': ('Paediatrics','Haemolytic Uremic Syndrome','post-diarrheal HUS E coli O157'),
'q1527': ('Paediatrics','Coagulation Disorders','factor XIII deficiency urea clot'),
'q1528': ('Paediatrics','Cystic Fibrosis','features of cystic fibrosis'),
'q1529': ('Biochemistry','Inborn Errors of Metabolism','alkaptonuria black urine'),
'q1640': ('Pharmacology','Antidiabetic Drugs','SGLT2 inhibitor candidiasis'),
'q1641': ('Surgery','Breast Cancer','HER2 breast lapatinib'),
'q1642': ('Medicine','Lung Cancer','osimertinib T790M'),
'q1643': ('Orthopaedics','Pelvic Fractures','pelvic fx hemorrhage binder'),
'q1644': ('Anatomy','Upper Limb Nerves','ulnar nerve lesion hand'),
'q1645': ('Surgery','Hernias','reduction en masse'),
'q1646': ('Surgery','Abdominal Anatomy','3rd part duodenum anterior relations'),
'q1647': ('Surgery','Varicocele','varicocele venous drainage'),
'q1648': ('Medicine','Tuberculous Meningitis','TB meningitis CSF findings'),
'q1649': ('Medicine','Thyroid Disorders','hyperthyroidism labs'),
'q1650': ('Medicine','Electrolyte Disorders','hyperkalemia tented T waves'),
'q1651': ('Paediatrics','Diabetic Ketoacidosis','ISPAD pediatric DKA protocol'),
'q1876': ('OBG','Contraception','DMPA bleeding UPT next step'),
'q1877': ('OBG','Ovarian Tumors','virilizing ovarian tumor'),
'q1878': ('Paediatrics','Cystic Fibrosis','CF sweat chloride physiology'),
'q1879': ('OBG','Uterine Inversion','inversion placenta attached reposition'),
'q1880': ('Anaesthesia','Preoperative Assessment','ASA Physical Status classification'),
'q1881': ('OBG','Sexually Transmitted Infections in Women','genital HSV-2 ves admin'),
'q1882': ('Medicine','Adrenal Insufficiency','adrenal crisis hydrocortisone'),
'q1883': ('Medicine','Rickettsial Infections','fever eschar scrub typhus'),
'q1884': ('Medicine','Antitubercular Therapy','pyrazinamide hyperuricemia'),
'q1885': ('OBG','Rh Incompatibility','ICT titer 1:4 repeat after 4 weeks'),
'q2040': ('Paediatrics','Inherited Metabolic Disorders','Zellweger syndrome peroxisomes'),
'q2041': ('Dermatology','Skin Tumors','basal cell carcinoma'),
'q2042': ('Anaesthesia','Airway Management','RSI statement false cardiac arrest'),
'q2043': ('Medicine','Endocrinology','Kallmann syndrome anosmia'),
'q2044': ('Medicine','Pharmacology in Liver Disease','safest benzo liver failure lorazepam'),
'q2045': ('Medicine','Spinal Cord Disorders','identify spinal cord lesion'),
'q2046': ('Medicine','Arrhythmias','stable SVT adenosine'),
'q2047': ('Medicine','Spinal Cord Disorders','Brown-Sequard not complete transection'),
'q2048': ('OBG','Contraception','LARC vs sterilization'),
'q2049': ('OBG','Antenatal Care','period of gestation LMP'),
'q2050': ('OBG','Contraception','Pearl index failure rate'),
'q2051': ('OBG','Amenorrhea','primary amenorrhea definition'),
'q2052': ('OBG','Vaginal Cancer','DES clear cell adenocarcinoma'),
'q2053': ('OBG','Dystocia','causes of uterine dysfunction'),
'q2054': ('OBG','Placental Abruption','abruption not painless bleeding'),
'q2055': ('OBG','Diagnosis of Pregnancy','probable signs 8 weeks'),
'q2056': ('OBG','Oral Contraceptives','noncontraceptive uses OCPs'),
'q2057': ('OBG','Amenorrhea','Turner syndrome primary amenorrhea'),
'q2058': ('OBG','Postpartum Hemorrhage','AMTSL correct sequence'),
'q2059': ('OBG','Vulvar Lesions','risk factors vulval carcinoma'),
'q2060': ('OBG','Obstetric Terminology','vagitus uterinus definition'),
'q2223': ('Anatomy','Male Reproductive Histology','seminiferous tubule cell order'),
'q2224': ('Dermatology','Leprosy','ENL in pregnancy MDT'),
'q2236': ('Dermatology','Papulosquamous Disorders','collarette and silvery scales'),
'q2348': ('OBG','Preeclampsia & Eclampsia','premonitory symptoms of eclampsia'),
'q2349': ('OBG','PCOS','PCOD management'),
'q2350': ('OBG','Fetal Anomalies','anencephaly USG second trimester'),
'q2351': ('OBG','Cervical Screening','Pap smear collection order'),
'q2352': ('OBG','Postpartum Hemorrhage','AMTSL components'),
'q2353': ('OBG','Amenorrhea','secondary amenorrhea causes not Kallmann'),
'q2354': ('OBG','Infertility','semen morphology normal 4%'),
'q2355': ('Medicine','COVID-19','COVID discharge morning glucose mucormycosis'),
'q2356': ('Medicine','Stroke','acute stroke thrombolysis'),
'q2357': ('Medicine','SIADH','SIADH incorrect statement urinary sodium'),
'q2358': ('Medicine','Headache Disorders','cluster headache sumatriptan sc'),
'q2359': ('Medicine','Valvular Heart Disease','mitral stenosis wal image'),
'q2360': ('Medicine','Myocarditis','endomyocardial biopsy myocarditis'),
'q2361': ('Orthopaedics','Osteoporosis','osteoporosis calcium ALP labs'),
'q2362': ('Paediatrics','Congenital Heart Disease','TAPVC equal saturation all chambers'),
'q2363': ('Psychiatry','Organic Mental Disorders','Korsakoff amnesia'),
'q2364': ('Medicine','Ergotism','ergotamine with ART vasospasm'),
'q2365': ('Medicine','Disorders of Consciousness','GCS intubated verbal NT'),
'q2366': ('Anatomy','Brachial Plexus Nerve Injury','axillary nerve deltoid shoulder vaccine'),
'q2367': ('Anatomy','Cranial Nerves','lower cranial nerve injury dysphagia'),
'q2368': ('Medicine','Motor Neuron Disease','ALS diagnosis'),
'q2369': ('Medicine','Transfusion Reactions','TRALI leukocyte antibodies'),
'q2370': ('Medicine','Cardiac Failure','right heart failure image'),
'q2371': ('Anaesthesia','Anaesthesia Equipment','capnography yellow tracing'),
'q2372': ('Pharmacology','Antitussives','centrally acting opioid antitussive'),
'q2373': ('ENT','Adenoid Hypertrophy','adenoid facies'),
'q2561': ('OBG','Urogynaecology','LUTS symptoms'),
'q2562': ('OBG','Prolapse','uterocervical prolapse image'),
'q2563': ('OBG','Ovarian Cysts','ovarian cyst follow up 6 weeks premenopausal'),
'q2564': ('Orthopaedics','Fractures','fracture classification matching'),
'q2565': ('Orthopaedics','Orthopaedic Examination','Thomas test sequence'),
'q2566': ('Orthopaedics','Osteoporosis','osteoporosis alendronate after Colles'),
'q2567': ('Orthopaedics','Compartment Syndrome','anterior compartment pressure'),
'q2568': ('Orthopaedics','Bone Tumors','bone tumor treatments matched'),
'q2569': ('Orthopaedics','Bone Tumors','duplicate bone tumor treatments'),
'q2570': ('Paediatrics','Developmental Milestones','milestone matching'),
'q2571': ('Paediatrics','Primary Immunodeficiencies','DiGeorge defect'),
'q2739': ('Dermatology','Urticaria','amoxicillin urticaria'),
'q2740': ('Dermatology','Sexually Transmitted Infections','chancroid school of fish'),
'q2741': ('Dermatology','Annular Skin Lesions','annular lesion'),
'q2742': ('Dermatology','Contact Dermatitis','patch test contact dermatitis'),
'q2781': ('OBG','Placental Abruption','abruption woody uterus'),
'q2800': ('OBG','Placenta Previa','painless bright red bleeding'),
'q2819': ('OBG','Preeclampsia & Eclampsia','seizure prophylaxis Mg'),
'q2838': ('OBG','Placenta Previa','complete previa 32wk admission'),
'q2857': ('OBG','Placenta Previa','recurrent prepa previa'),
'q2876': ('OBG','Placenta Previa','previa 32wk expectant steroids'),
'q2895': ('OBG','Preeclampsia & Eclampsia','Mg toxicity antidote'),
'q2914': ('OBG','Placenta Previa','USG localize previa'),
'q2933': ('OBG','Preeclampsia & Eclampsia','HELLP urgent delivery'),
'q2952': ('OBG','Placenta Previa','painless causeless bleeding previa'),
'q614': ('OBG','Fetal Monitoring','non-reactive NST next step modified BPP'),
'q615': ('OBG','Diagnosis of Pregnancy','probable vs presumptive signs of pregnancy'),
'q616': ('OBG','Obstetric Fistula','vesicovaginal fistula after obstructed labour'),
'q617': ('OBG','Amenorrhea','AIS primary amenorrhea absent uterus testes'),
'q618': ('OBG','Amenorrhea','imperforate hymen hematometrocolpos'),
'q619': ('OBG','Abnormal Uterine Bleeding','perimenopausal thickened endometrium biopsy'),
'q620': ('OBG','Postmenopausal Bleeding','postmenopausal bleeding workup'),
'q621': ('OBG','Assisted Reproduction','OHSS after hMG stimulation'),
'q622': ('OBG','Operative Hysteroscopy','TURP syndrome fluid overload myomectomy'),
'q623': ('OBG','Prolapse','cardinal ligament uterine support'),
'q624': ('OBG','Infections in Pregnancy','toxoplasmosis IgG positive IgM negative'),
'q625': ('OBG','Gestational Diabetes Mellitus','insulin does not cross placenta'),
'q626': ('OBG','Normal Labour','partograph action line crossing'),
'q627': ('OBG','Cervical Cancer','FIGO IIIB hydronephrosis parametrial'),
'q628': ('OBG','Vulvar Lesions','vulvar cancer FIGO stage IIIB'),
'q629': ('OBG','Vaginal Infections','trichomonas frothy discharge strawberry cervix'),
'q630': ('OBG','Medical Abortion','MTP beyond 24 weeks medical board'),
'q631': ('OBG','Induction of Labour','IOL contraindications post-maturity'),
'q632': ('OBG','Antenatal Care','CRL best dating 8 weeks'),
'q633': ('OBG','Amenorrhea','premature ovarian insufficiency FSH AMH'),
'q634': ('OBG','Physiological Changes in Pregnancy','hemoglobin decreases in pregnancy'),
'q635': ('OBG','Preeclampsia & Eclampsia','acute fatty liver third trimester'),
'q636': ('OBG','Preeclampsia & Eclampsia','magnesium toxicity respiratory depression'),
}

missing = [q['qid'] for q in obg if q['qid'] not in M]
extra = [k for k in M if k not in byid]
print('OBG count:', len(obg), 'mapped:', len(M))
print('missing:', missing)
print('extra:', extra)